[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 7
padding.y = 7
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]


# Pink Cat Boo - Alacritty theme

[colors.primary]
background = "#202330"
foreground = "#FFF0F5"
dim_foreground = "#9498a1"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#202330"
cursor = "#FFEDF0"

[colors.vi_mode_cursor]
text = "#202330"
cursor = "#FE7C8E"

[colors.search.matches]
foreground = "#202330"
background = "#F3B4BF"

[colors.search.focused_match]
foreground = "#202330"
background = "#FE7C8E"

[colors.hints.start]
foreground = "#202330"
background = "#FE7C8E"

[colors.hints.end]
foreground = "#202330"
background = "#F3B4BF"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#202330"
background = "#FFF0F5"

[colors.selection]
text = "#FFF0F5"
background = "#472541"

[colors.normal]
black   = "#202330"
red     = "#FF4C7A"
green   = "#3BC089"
yellow  = "#D0963A"
blue    = "#6767CE"
magenta = "#C77DFF"
cyan    = "#4CC9C0"
white   = "#FFF0F5"

[colors.bright]
black   = "#565970"
red     = "#FF7F9D"
green   = "#9CD162"
yellow  = "#FEC831"
blue    = "#A2C2EB"
magenta = "#E6A1FF"
cyan    = "#75E0D6"
white   = "#FFFFFF"

[colors.dim]
black   = "#15171F"
red     = "#8A2B48"
green   = "#296B50"
yellow  = "#7A5A22"
blue    = "#3D3D82"
magenta = "#7A4D99"
cyan    = "#2E7A73"
white   = "#8E8E8E"

